### ISSUE TITLE
As a performer, I need to be able to submit stage plots as PDF.

### ISSUE THREAD

**Issue by cybersenshi** [magfest/bands#38]
Currently not allowed, but also most common format.

**Comment by kitsuta** [comment]
This is a config option, but we'll need to add it in puppet.

**Comment by binary1230** [comment]
If this can be changed in configspec.ini, that's cool too, it's a reasonable default

**Comment by kitsuta** [comment]
Hmm, fair point.

**Comment by kitsuta** [comment]
Uh, it's already in there. https://github.com/magfest/bands/blob/master/bands/configspec.ini#L9

**Comment by binary1230** [comment]
Quickly tested and confirmed this works
