### ISSUE TITLE
as a music admin, I'd like an easier way to create bands

### ISSUE THREAD

**Issue by binary1230** [magfest/bands#51]
Currently to create a band an admin has to go through a lengthy multi-page process of:
1) create a group
2) fill in info for badge in that group
3) mark that badge as a leader
4) go to the band page, make that group as a badge

would be cool if we could at least add a shortcut to "type in an email address, first name, last name" and it creates a group, marked as a band, with a group leader marked as placeholder, and then takes you to /uber/band_admin/band_info?id=whatever

would save a ton of time when a music admin wants to create 6 bands at the same time.  I think this is relatively easy to do, but..... who knows : )

**Comment by binary1230** [comment]
from mike: also be able to specify # of people in the group

**Comment by binary1230** [comment]
todo: check on what actually triggers the email to the band leader, and probably make sending each individual email a manual checkbox on the admin page like 'clear to send email', if that's not already an easily controllable thing

**Comment by binary1230** [comment]
for more detailed info on the process, this doc here has it outlined:
https://docs.google.com/document/d/1T0an1z1XcPpFMZh9eAhCIzs5RNYWTsNGXFCcvGyBq24/edit#heading=h.6q7zv58oxalr

I am proposing we automate the entire section of that doc before the section marked 'Marking a group as a band'

**Comment by migetman9** [comment]
I looked into this a bit. 

I propose we modify the Add A Group Page, or groups/form.html, to recognize if the band plugin is present. If present display a checkbox currently titled "Is A Band". When checked a set of fields will appear to allow input for the First, Last, and Email of a band leader. 

This could automate the entire section including the "marking a group as a band". With this post are mock-ups of a UI conveying the idea. Little to no code has been written. I would love to hear tweaks or alternate proposals for a solution. 

<img width="810" alt="band1" src="https://cloud.githubusercontent.com/assets/6538753/26709808/4d125dd6-470a-11e7-9940-736b76f4ee67.png">
<img width="705" alt="band2" src="https://cloud.githubusercontent.com/assets/6538753/26709811/4f16d684-470a-11e7-840a-60342ee55635.png">
<img width="756" alt="band3" src="https://cloud.githubusercontent.com/assets/6538753/26709813/519da1da-470a-11e7-8ee7-72d7cbd640f0.png">
<img width="540" alt="band4" src="https://cloud.githubusercontent.com/assets/6538753/26709814/559199d6-470a-11e7-971c-c333334e4cb6.png">

**Comment by kitsuta** [comment]
Super cool mockups, @migetman9!

The only wrinkle with this approach is that as a rule, the 'core' plugin is not really allowed to know about feature plugins. We want the system to work on its own, and it could be pretty tricky to program this to work both with and without the band plugin present.

I actually filed issue https://github.com/magfest/ubersystem/issues/2120 which is related to this, in the sense that "plugins can inject things into our forms" is a use-case we already want. I'm not sure if there's another way to do this without having that be possible.

**Comment by binary1230** [comment]
I actually was thinking about the approach where to go to the bands page,
click a new button named 'add a new band', fill in those couple of fields,
and behind the scenes it creates all the group stuff and lands you on the
band admin page next.   I.e. The band admin never has to visit the groups
page to make a band

Open to whatever though

**Comment by migetman9** [comment]
I'm in agreement with @binary1230 for an 'add a new band' button.

**Comment by kitsuta** [comment]
Yeah, sounds like a solid approach.

**Comment by RobRuana** [comment]
Fixed by #64.
