### ISSUE TITLE
Leader of bands made through new method have different pay status.

### ISSUE THREAD

**Issue by migetman9** [magfest/bands#67]
Leader of bands created through the new band creation page is marked as c.NEED_NOT_PAY instead of c.PAID_BY_GROUP (?) 

<img width="837" alt="screen shot 2017-06-06 at 6 11 17 pm" src="https://user-images.githubusercontent.com/6538753/26858219-d33a6254-4ae4-11e7-975b-754aecb562af.png">

**Comment by Hachi05** [comment]
Resolves https://github.com/magfest/magstock/issues/129 -- thanks!
